### ISSUE TITLE
Unexpected syntax highlighting when using trailing backslashes

### ISSUE THREAD

**Issue by cdrini** [bearmini/vscode-systemd-unit-file#2]
![image](https://user-images.githubusercontent.com/6251786/40874315-b973d058-663b-11e8-97d7-0021f38c2235.png)

> Lines ending in a backslash are concatenated with the following line while reading and the backslash is replaced by a space character. This may be used to wrap long lines.
> https://www.freedesktop.org/software/systemd/man/systemd.unit.html

**Comment by bearmini** [comment]
Hi @cdrini,

Thank you for reporting the issue and sorry I have not noticed this until now.

I have fixed the issue and published as 1.0.2.

Enjoy!
