### ISSUE TITLE
User= Group= not highlighted red as other keywords

### ISSUE THREAD

**Issue by jkornblum** [bearmini/vscode-systemd-unit-file#3]
Based on these Ubuntu [docs](http://manpages.ubuntu.com/manpages/bionic/man5/systemd.service.5.html), I think `User=` and `Group=` are valid keywords under [Service]. They do not seem to highlight the same as other keys. I'm not `systemd` expert so maybe they shouldn't?

**Comment by bearmini** [comment]
Hi @jkornblum, thank you for reporting the issue!
I just have released ver 1.0.3 which includes systemd.exec(5) keywords like `User=` and `Group=`.

**Comment by bearmini** [comment]
Closing this issue as I released the new version. If you find any further issues, please let me know.
