### ISSUE TITLE
StartLimitIntervalSec not highlighted

### ISSUE THREAD

**Issue by breversa** [bearmini/vscode-systemd-unit-file#7]
Hello !

Is it normal that `StartLimitIntervalSec` in `[Unit]` is not highlighted ?

I stumbled upon it by reading this : https://medium.com/@benmorel/hi-it-looks-like-startlimitintervalsec-is-the-new-name-introduced-in-systemd-230-e56ca3f57c02

**Comment by bearmini** [comment]
@breversa Hello! Thank you for letting me know it. I have updated and published the extension ver 1.0.6. Enjoy!

Please let me know if it doesn't work.

Thank you!

**Comment by breversa** [comment]
Hello !
Only 14 hours between opening the issue, and the correction being published ? You’re AWESOME ! :D :D
